### ISSUE TITLE
Scandoubler Effects and YPbPr

### ISSUE THREAD

**Issue by tonytoon** [MiSTer-devel/Main_MiSTer#260] opened 2020-06-29 16:57 UTC
When I switched from using VGA to component video on a 15Khz consumer crt it took me a while to figure out that several of my cores were displaying a rolling image because scan doubler effects were still enabled. Since I didn’t know that was the cause at the time, and couldn’t see the menus I ended up doing a wipe and reinstall of my SD card.

Would it be prudent to automatically disable scan doubler effects when outputting via YPbPr? They seem hit and miss in that output mode, and put the system into a failure state that is unintuitive to fix.

**Comment by sorgelig** [comment] 2020-06-29 18:09
YPbPr is not limited to 15KHz. 480p/512p over component is pretty much valid option.
if forced_scandoubler=0 in INI file then it will be up to specific core if it provides normal or scandoubled mode. Main cannot control this.

**Comment by sorgelig** [comment] 2020-11-17 09:07
Closing as not an issue. It's the matter of specific display compatibility. Not a bug.

**Closed by sorgelig** 2020-11-17 09:07 UTC
