### ISSUE TITLE
When a file is missing OSD says 'Missing directory'

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/Main_MiSTer#369] opened 2021-03-28 08:11 UTC
If you load a game/disk image from e.g. Minimig's OSD and then delete that file over FTP or SSH and then try to load another game the OSD says:

No files!

Missing directory:
Amiga

... even though the directory is there and there are files in it.

**Comment by sorgelig** [comment] 2021-03-28 09:27
duplicate of https://github.com/MiSTer-devel/Main_MiSTer/issues/364

**Closed by sorgelig** 2021-03-28 09:27 UTC
