### ISSUE TITLE
Keyboard shortcut for USER button doesn't work when defining buttons

### ISSUE THREAD

**Issue by sofakng** [MiSTer-devel/Main_MiSTer#285] opened 2020-09-14 19:05 UTC
The user shortcut for USER (LCtrl+LAlt+RAlt, or redefined in mister.ini) doesn't appear to work when defining joystick buttons (in the mister menu, and in core menus).

For example, when you define a joystick in the main mister menu, the second prompt asks for "Stick 1 Test: Tilt RIGHT":
![E9auHQTm](https://user-images.githubusercontent.com/2228499/93127272-977ae980-f69b-11ea-8df8-d93a2d636957.jpg)

It says you can press "User/Space" to leave it undefined, however if you use the keyboard shorcut for USER it doesn't work.  Spacebar does work though.  The user keyboard shortcut also works correctly when using a core (ie. reset) but not when defining buttons.

**Comment by sorgelig** [comment] 2020-09-16 10:20
There are no keyboard shortcuts for USER button. It's button on I/O board (also one of two buttons on de10-nano). No idea what you are talking about.

**Comment by sofakng** [comment] 2020-09-16 13:10
I'm talking about this wiki article:  https://github.com/MiSTer-devel/Main_MiSTer/wiki/Keyboard

It shows the following:

> Common functional keys/combos used in cores
> F12 - open/close OSD menu/submenu
> Alt-F12 - quick core selection (like in Menu core).
> **LCtrl+LAlt+RAlt - presses the "USER" button which usually is reset in emulated system.**
> LShift+LCtrl+LAlt+RAlt - MiSTer reset (load Menu core).

**Comment by sorgelig** [comment] 2020-09-16 14:26
It's only for cores. 
Once OSD is opened, core-specific mappings aren't available.
This is by design.

**Comment by sorgelig** [comment] 2020-11-17 09:02
closing it as it's not an issue but the way it supposed to work.

**Closed by sorgelig** 2020-11-17 09:02 UTC
