### ISSUE TITLE
First controller input is consequently ignored in OSD

### ISSUE THREAD

**Issue by littlegamer87** [MiSTer-devel/Main_MiSTer#537] opened 2022-02-13 13:56 UTC
As a minor issue, I would like to report that the MiSTer appears to ignore the first controller input when the device is powered on.
Controller used is a Switch Pro over Bluetooth (TP-Link UB400)

Steps to reproduce: Power on the MiSTer, allow time to load bluetooth and pair with the controller. The first input on the controller to control the OSD (dpad or buttons) is never processed. Waiting to press a button after pairing changes nothing. The second input press always works, and the ones after that too.

When loading a core, the issue reappears. EG after loading the SNES core (which requires me to operate the OSD after booting, where the first input is missed), the first input in the SNES OSD is missed as well. The GBA core does not open the OSD by default, what's interesting is that pressing the OSD button after loading the core (which I assigned to the home button on my controller), brings up the OSD without missing the input. After the OSD appears, the first input is missed again.

Tested on v220211, OS v211112

**Comment by birdybro** [comment] 2022-02-13 15:44
I think this is intentional. Whatever controller receives a button input first upon loading a core becomes "Player 1". Whatever controller receives a button press second is assigned to "Player 2", and so on...

**Comment by littlegamer87** [comment] 2022-02-13 18:14
Thanks for your feedback. I understand your reasoning but is it required to ignore the input for that?

**Comment by paulb-nl** [comment] 2022-02-13 18:35
I am not able to reproduce this with a wired controller. First input always works.

**Comment by sorgelig** [comment] 2022-02-13 18:39
I cannot reproduce it using Bluetooth controller (Apex 2).

**Comment by birdybro** [comment] 2022-02-13 19:02
Ah I must have misunderstood you. I tend to do that. I cannot reproduce that with a DualSense (DS5) or an 8bitDo SN30 Pro 2. I also paired a Switch Pro controller with the 8BitDo adapter, same result, it registers on first press. 

However, I **was** able to reproduce it when I used my Edimax BT500 bluetooth adapter to pair the Switch Pro controller.

First time I press down (nothing happens on screen):

```
057e:2009:00 P0 Input event: type=EV_ABS, Axis=17 [-1...1], Offset=1
Device A4:38:CC:6D:6D:23 assigned to player 1
FileOpenEx(open) File:/media/fat/config/kbd_057e_2009.map, error: No such file or directory.
PS2 code(make)(ext) for core: 114(0x72)
057e:2009:00 P1 Input event: type=EV_ABS, Axis=4 [-32767...32767], Offset=1510
PS2 code(break)(ext) for core: 114(0x72)
```

Second time:

```
057e:2009:00 P1 Input event: type=EV_ABS, Axis=17 [-1...1], Offset=1
PS2 code(make)(ext) for core: 114(0x72)
057e:2009:00 P1 Input event: type=EV_ABS, Axis=17 [-1...1], Offset=0
PS2 code(break)(ext) for core: 114(0x72)
```

Also this controller has motion sensing inside, which can create a lot of noise in the terminal. Here's a video showing what happens:

https://user-images.githubusercontent.com/16388068/153770457-d36d646b-e55c-406c-ba8e-605c265be95a.mp4

**Comment by littlegamer87** [comment] 2022-02-13 23:16
I am extremely grateful for the incredible support given. I have no means to build from source, looking forward to test this once released

**Comment by birdybro** [comment] 2022-02-14 00:42
The changes I made were flawed, the next PR I submitted fixes my mistakes. The change I made wasn't likely to fix the behavior you noticed, however it did get rid of the Switch Pro spamming the logs with accelerometer data.

[MiSTer.txt](https://github.com/MiSTer-devel/Main_MiSTer/files/8057075/MiSTer.txt)

Rename this to just MiSTer and test it out.

**Comment by birdybro** [comment] 2022-02-14 18:44
Interesting... Okay then I should just revert the change. This was a good lesson for me to learn.

**Closed** 2022-10-31 15:12 UTC
