### ISSUE TITLE
Proposal: Add dvi_mode to MiSTer.ini

### ISSUE THREAD

**Issue by umatthe** [MiSTer-devel/Main_MiSTer#7] opened 2017-11-14 19:55 UTC
Currently only HDMI Monitors are supported by MiSTer. 
To support DVI Monitor only the "HDMI Bit" in the hdmi initialisation needs to be cleared.
A new config switch in MiSTer.ini like:

dvi_mode=1 ; set to 1 for DVI-Monitor

could enable the usage of those displays.
I have already working a demo implementation of this feature (MiSter and a modified C64-Core). Because almost all MiSTer cores use the same framework this little patch would enable all cores to be working on my DVI displays.

**Comment by sorgelig** [comment] 2017-11-14 23:28
DVI mode doesn't support Audio.
MiSTer is tweaked to output video to TV, not monitor.

**Comment by umatthe** [comment] 2017-11-15 00:03
I know that DVI has no audio. Audio can be connected via the IO-Board in this case.
The configuration option I would like to see added, is very small, does not disturb the HDMI mode and adds lot of monitors to the list of supported displays. 

If I could build the .rbf Files with this HDMI-Bit made configurable myself, I would just do it, but without the full Quartus version this is not possible. Maybe I should send You my little changes I made and You decide if it might be useful for other people too. So far I tried my patch for C64, Arcade_Pacman and Menu_Mister.

**Comment by sorgelig** [comment] 2017-11-15 09:42
Send me your changes, or create a pull request. I don't give guaranty it will be included in exactly this form. But since you've tested it, it will be useful for patch. HDMI has powering on problem (cannot output the video if DE10-nano has been powered before the monitor/TV). I'm sure it's due to configuration of HDMI chip. I will need to find and fix the problem. And at the same time i can include the option for DVI. 

If you are interested and have a time, try to find where is the powering problem. That would help a lot!

**Comment by umatthe** [comment] 2017-11-15 16:36
ok - I added a pull request for the Main_MiSTer code.
I will submit a pull request for the C64 cores. If You approve the changes I could do them for the remaining cores.

I just tried in DVI Mode: The order of powering up the Monitor and DE10-nano is not important, I have always a picture.

**Comment by umatthe** [comment] 2017-11-22 12:25
I did some tests with an HDMI Monitor and could not see the problem You mentioned.
I tried to power up the DE10-nano with the Monitor switched off and with the Monitor completely disconnected from power. In both cases the screen showed the OSD-Menu after the monitor was powered up. The only way to reproduce Your problem was to startup the DE10-nano without the monitor cable connected. After connecting the cable (while the DE10-nano is running) there was no output on the screen. But normally I would try to avoid connecting the cable while the equipment is running.

**Comment by sorgelig** [comment] 2017-11-22 16:37
I'm glad that you reproduced the problem. For you it happens only if you power on DE10 disconnected, but for me it happens even if it's connected but with powered off monitor. I think it depends on Monitor's HDMI circuit and how it's powered. 
But the problem exists.

**Comment by umatthe** [comment] 2017-11-24 14:21
I played a little with the Hot Plug config of the HDMI and now I have a modifcation running on my setup without any problems. I can startup the DE10-nano without cable connected, after I plug in the cable the display works. The 2 attached files are from the Menu_MiSTer project that I used for testing.


[sys_top.v.gz](https://github.com/MiSTer-devel/Main_MiSTer/files/1501876/sys_top.v.gz)
[hdmi_config.sv.gz](https://github.com/MiSTer-devel/Main_MiSTer/files/1501877/hdmi_config.sv.gz)

**Comment by sorgelig** [comment] 2017-11-25 11:23
Unfortunately it's not the solution. Otherwise simple reset of MiSTer would make video appear. Resend the i2c config on HPD is nothing else than simple restart the core.
Unfortunately it doesn't solve the problem.

**Comment by umatthe** [comment] 2017-11-25 12:14
Did You try it with Your setup? In my case (powerup without cable connected) a reset of the MiSTer does not help, but my modification solved the problem.

**Comment by sorgelig** [comment] 2017-11-25 18:56
Yes. I've tried it. It doesn't solve the problem. Actually HPD is not an issue at all. If you press a hard reset button, then HDMI chip will be re-programmed when Menu core loaded. 
Something in HDMI chip is not initialized by i2c and remained in the sleep status. On power-on sequence chip does some HDMI tests which is not triggered on i2c config. So, need to find how to re-init the HDMI chip fully, so it will think it's power-on sequence.

**Comment by sorgelig** [comment] 2017-11-25 20:46
ok. It seems i've found how to fix it.

**Comment by sorgelig** [comment] 2017-11-26 15:58
Monitor sense flag was the source of problem. By the way, in my case i never get HPD triggered when i switch the Monitor on later than DE10. Probably HPD is triggered only when you physically re-plug the HDMI cable. Anyway, now USER button in Menu core re-inits the HDMI.

Back to DVI mode. Probably i will need to think about alternative resolution for DVI. Usually those ancient monitors with DVI instead of HDMI won't accept the 1280x720. Something like 1280x1024 (standard for 19" monitors) should be better. I remember i've already tried to make resolutions switchable and failed by forgotten reason.

**Comment by umatthe** [comment] 2017-11-27 10:25
Little by little is ok for me. :-) 
I have some DVI-Monitors (some are quiet old 15", 1280x1024 ones) - all of them work with just the DVI-Bit set in the configuration.

**Comment by sorgelig** [comment] 2017-12-14 18:24
Test version of DVI and more HDMI resolutions are added into ZX and BK0011M cores.
Read more here: http://www.atari-forum.com/viewtopic.php?f=117&t=32774

**Comment by sorgelig** [comment] 2018-05-02 15:16
done

**Closed by sorgelig** 2018-05-02 15:16 UTC
