### ISSUE TITLE
Bluetooth controller D-pad stops working after Bluetooth keyboard goes to sleep

### ISSUE THREAD

**Issue by c0d3h4x0r** [MiSTer-devel/Main_MiSTer#242] opened 2020-06-07 07:57 UTC
I use a DIERYA DK61 Bluetooth keyboard and an 8-bitdo M30 Bluetooth gamepad with a Bluetooth USB dongle with my MiSTer.

Whenever I have both devices on and connected and working, and then I start playing a game (using any core) using the gamepad, the moment the keyboard goes to sleep due to inactivity, the D-pad on my controller stops responding.  The buttons on it still work, however.  To fix it, I have to wake the keyboard up so it reconnects.  The only way I have found to avoid this is to manually power down the keyboard before launching a core — but this is not a viable workaround when using computer cores (such as Minimig) to play a game.

Is there some way the Bluetooth handling can be fixed so that when my keyboard goes to sleep, the game controller will keep working?

**Comment by sorgelig** [comment] 2020-06-07 08:59
This is specific to your BT devices. Never had such problem. May be keyboard sends some codes confusing the dongle or system when going to sleep. 
I only can suggest to use other BT keyboard.

**Comment by sorgelig** [comment] 2020-06-07 09:00
I close this issue as it's definitely not related to Main.
Any linux related issues should be discussed on forum. In most cases they are not related to Main (such as this one).

**Comment by c0d3h4x0r** [comment] 2020-06-07 09:20
Definitely not a problem with my Bluetooth keyboard, as this problem does not happen when using thr same keyboard, controller, and Bluetooth dongle with my HTPC or my Raspberry Pi.  It only happens with MiSTer, so it’s definitely a MiSTer problem of some kind.

**Comment by sorgelig** [comment] 2020-06-07 09:51
You don't understand what is open source hobby project. It's not like "i have problem - you have to fix." I have no devices you use, so most likely i won't fix it, as i have no such issue.
Tested keyboards and gamepads are discussed on forum. If you want to provide fixes for other devices - you are welcome.

**Comment by c0d3h4x0r** [comment] 2020-06-07 19:12
I understand perfectly well that this is an open source hobby project.  I never said you have to fix it.  I just said it’s definitely a MiSTer problem.  No need to take it personally.

**Comment by c0d3h4x0r** [comment] 2020-06-19 05:39
Can this please be reopened?  I think I’ve figured out what’s happening.  When the Bluetooth keyboard goes to sleep, the game controller becomes a different input device number, and that’s why it *appears* to stop working.  It actually still works just fine to bring up and operate the OSD, but the core doesn’t think it’s controller #1 anymore.  This seems like a legitimate issue with how MiSTer handles input device assignments.  My expectation is that if a keyboard device suddenly disappears, that shouldn’t cause game controllers to get renumbered.

**Comment by c0d3h4x0r** [comment] 2020-06-19 05:47
In fact, when this happens, if the core (such as MegaCD) supports a “Swap Joysticks” setting, and I toggle it, then the controller is once again recognized by the core as the Player 1 controller, until I wake the keyboard up again (then I have to toggle the setting again).  So that shows that when the keyboard goes to sleep, the Player 1 controller is somehow becoming the Player 2 controller, and when the keyboard wakes upC the controller becomes the Player 1 controller again.

**Comment by c0d3h4x0r** [comment] 2020-06-19 05:49
This may not even be a Bluetooth-specific thing; I’ll try it later with a wired USB gamepad and a wired USB keyboard, and see if I can repro by simply unplugging the keyboard after a core is running.

**Comment by c0d3h4x0r** [comment] 2020-06-20 19:57
This might have something to do with udev rules, so I'm digging into that side of it a bit.

First, I see `/etc/udev/rules.d` contains a couple ordinary (non-symlink) files, which (according to [this documentation](https://wiki.debian.org/udev) I found) are not used by `udevd`.  Apparently the daemon only actually reads and uses the rules under `/lib/udev/rules.d`.  So it seems the rules defined under `/etc/udev/rules.d` aren't actually being applied.

Second, `/lib/udev/rules.d/60-persistent-input.rules` seems highly likely to be involved with this repro, so I'm turning my attention there.

Third, I've found some udev rules for preventing auto-suspend of wired USB devices, and that made me wonder: is it possible to simply prevent the Bluetooth keyboard from going to sleep in the first place?  That might be a different (better?) approach to resolving this issue.

**Comment by sorgelig** [comment] 2020-06-20 23:30
BT should be able to sleep. It's by device design. They have limited battery.

**Comment by c0d3h4x0r** [comment] 2020-06-21 02:20
Alright, I think I've finally figured out the cause of this issue.  It is a code problem in MiSTer main.

The Bluetooth keyboard and game controller are each represented by `/dev/input/event*` nodes, 
 which get dynamically created/removed as devices are connected/disconnected.  When a Bluetooth device goes to sleep, it's the same as a disconnection.  And the mapping between event node number and device changes depending upon the order in which you connect and disconnect devices.

My Bluetooth keyboard gets 4 consecutively-numbered `event*` nodes, and my Bluetooth gamepad gets a single `event*` node.  When I power on my MiSTer, connect my keyboard, and then connect my gamepad, this is what I get under `/dev/input`:

```
/dev/input/event0 = MiSTer virtual device
/dev/input/event1 = Bluetooth keyboard
/dev/input/event2 = Bluetooth keyboard
/dev/input/event3 = Bluetooth keyboard
/dev/input/event4 = Bluetooth keyboard
/dev/input/event5 = Bluetooth gamepad
```

The big `while` loop at https://github.com/MiSTer-devel/Main_MiSTer/blob/master/input.cpp#L2731 loops over `/dev/input/event*` nodes (in whatever non-guaranteed order they are returned by `readdir()`) and assigns the first `NUMDEV` (30) of them to the `input` and `pool` arrays.  (Note that a `for` loop is used to reinitialize both arrays before this `while` loop.)

Let's assume (for the sake of example, and since it appears to hold true) that `readdir()` returns all the `/dev/input/event*` nodes in numeric order.  When my keyboard goes to sleep, even though my gamepad is still represented by `/dev/input/event5`, it now occupies index 1 in the `input` and `pool` arrays, rather than index 5 as it did before.  This changes which device the core sees as which device number when an input callback is performed.

I think the right solution to this issue would be to change the `for` loop to leave array entries alone that still correspond to valid `/dev/input` nodes and change the `while` loop to only populate "blank" entries for `/dev/input` nodes that are not already in the arrays.  That way the array indices and device numbers won't change for devices that remain connected when some other device gets disconnected.

Does that sound like the right approach to you?  If so, I can take a stab at coding up and self-testing the change.  I just don't want to start going down the totally wrong path.

**Comment by c0d3h4x0r** [comment] 2020-06-21 03:50
I've cross-compilation all set up and working on a private fork, so I'm going to start tinkering with this.  If I get it working, I'll send you a PR.

**Comment by sorgelig** [comment] 2020-06-21 06:05
Your observation missed the part when new is plugged/unplugged. So when MiSTer detects changes in input dir, it flushes all devices and reload everything. Your case is not unique - it happens for everyone. And this case is properly handled.

**Comment by c0d3h4x0r** [comment] 2020-06-21 08:50
No, I didn't miss that.  When a Bluetooth device goes to sleep, that's the same as unplugging it.  That causes all the devices to get flushed and reloaded, which repositions all of the other still-connected devices.  That is the bug.

I have a working fix in hand.  I have verified that it solves the problem.  I will send you a PR shortly.

**Comment by sorgelig** [comment] 2020-06-21 09:51
No, it's not a bug. After flushing all devices are treated as new.
Trying to keep devices is not a correct and more obscure way. There is no point to keep devices in their position as MiSTer doesn't care which device on which position.

**Comment by c0d3h4x0r** [comment] 2020-06-21 10:03
The point of keeping devices in their position is to prevent this bug.  It is not an acceptable user experience for their controllers to stop working just because their keyboard went to sleep.

Please tell me **why** you think it's bad to save device positions.  Give me a clear example where that is the wrong thing to do.

**Comment by sorgelig** [comment] 2020-06-21 15:01
1) This problem is unique to your setup. I never experienced this problem.
2) you didn't find the root of problem, so this is not a fix. 
I often plug/unplug input devices on the fly. And the method when a whole input subsystem is re-created is more clean way which doesn't accumulate possible problem.

Again, the root of problem should be identified and bug should be able to replicate on other devices to be a system bug. Otherwise it may be a bug of firmware of keyboard/dongle/gamepad.
When root of problem will be identified the fix can be different and more proper. May be there is a bug in BT stack or other Linux driver.

**Comment by c0d3h4x0r** [comment] 2020-06-21 19:53
Yes, I DID identify the root cause.  This problem is NOT unique to me.  It’s not my fault that you are too stubborn or impatient to read and understand the explanation I have handed to you on a silver platter.

Please re-read the explanation of the issue that I already gave you. Then re-read it again.  Then keep re-reading as many times as it takes for you to understand it.  Then, go work on your people skills.

I’ll be waiting for your apology.

**Comment by c0d3h4x0r** [comment] 2020-06-22 00:16
The revised approach works and is less code churn.  Please see the new PR here: https://github.com/MiSTer-devel/Main_MiSTer/pull/250

**Comment by c0d3h4x0r** [comment] 2020-06-22 00:19
When you review the PR, make sure to "Hide whitespace changes" in the diff settings, otherwise it looks like far more churn than it actually is.

**Comment by c0d3h4x0r** [comment] 2020-06-22 00:25
I encourage you to reproduce this issue for yourself:

**Repro steps:**
1. Turn on your MiSTer with no keyboard or controllers attached.
2. Plug in wired USB keyboard.
3. Plug in wired USB gamepad.
4. Launch the Sega Genesis core.
5. Load "Sonic the Hedgehog" and start playing.
6. While the game is running, disconnected the USB keyboard.

**Actual result:** Gamepad stops working.  You can use it to open and control the OSD, but it can no longer control the game.  This is because it now occupies the array position that was previously occupied by the keyboard.

**Expected result:** Gamepad should keep working.

And then I encourage you to clone my fork, build it, and try it out for yourself using the same repro steps.

**Comment by c0d3h4x0r** [comment] 2020-06-22 01:10
Or, are you trying to say that the ordering of the devices within the arrays shouldn't make any difference to the core?  Because all of my testing and investigation shows that the order currently **does** matter, and that the ordering **does** change when a device is disconnected.  The input callback happens for the same index as before the disconnection, but now there is a different (or no) device at that index.

If the ordering is not supposed to matter, and the callback that happens after disconnect is supposed to be using a different index to address the same device as before, then yes, there must be a defect somewhere else.  If that is what you have been trying to say, please confirm.

**Comment by c0d3h4x0r** [comment] 2020-06-22 02:24
Okay, I see where `input[i].num` is supposed to correspond to the core's virtual joystick number, and that's supposed to get passed into `joy_digital()`.  So it's possible the `input[i].num` values are simply not getting updated correctly across the device flush/recreate.  I will look into this angle further.

**Comment by c0d3h4x0r** [comment] 2020-06-22 02:32
Okay, I see... there's a loop in `input_cb()` that effectively tries to sequentially assign `input[i].num = i`, which totally destroys / changes the relationship between `input[i].devname` and `input[i].num`.  That's why the array element positions matter, when I guess they probably shouldn't.  I'm sorry for not understanding what you were driving at earlier; I'll chalk it up to the language barrier.

I'll try a third fix approach to properly preserve the `input[i].devname`-to-`input[i].num` relationship across flush/recreate of all the input devices.

**Comment by c0d3h4x0r** [comment] 2020-06-22 02:46
Alright, that approach works.  I'll close the previous PR and send this one to you instead.

**Comment by c0d3h4x0r** [comment] 2020-06-22 04:00
(Free advice: The fastest way to make someone mad and create drama is to blame them, dismiss them, and deny that there could be a bug in your code.  Next time, don't be so quick to blame the user; they might even be able to help!)

**Comment by c0d3h4x0r** [comment] 2020-06-22 04:42
I just hit a different bug with my third PR.  Investigating it.

**Comment by sorgelig** [comment] 2020-06-22 04:55
If you want to discuss personalities then i simply leave this thread. 
Your insulting is simply unacceptable. There are many other developers who collaborate without problem. You are acting like small child who didn't get the desired toy. 
While i'm trying to keep on topic, you are quickly get impatient and trying to insult me. This is definitely not a way to collaborate.

**Comment by c0d3h4x0r** [comment] 2020-06-22 04:56
Yeah, the problem is that udev device name can't be used as the map key, because that can change for the same device.  I need to use some other unique and invariant device identifier as the key.  I know there's one somewhere in this code that I should be able to use, because I can see it spit out by some of the log lines.

**Closed by sorgelig** 2020-06-22 04:55 UTC

**Comment by c0d3h4x0r** [comment] 2020-06-22 05:04
Looks `vid`+`pid` (and maybe also +`quirk`) together are what I need to use.

**Comment by sorgelig** [comment] 2020-06-22 05:26
I know what's happening and i have idea how to fix. This is because i found the root of issue which you didn't care of.  It has nothing to do with position in array.

**Comment by c0d3h4x0r** [comment] 2020-06-22 05:38
Using `vid`+`pid` as the unique key solved it.  PR updated.

**Comment by c0d3h4x0r** [comment] 2020-06-22 09:47
Please see the latest PR I sent to you.  I know you already made a change to try to fix part of the problem, but I found and fixed additional issues, and you might still want to pick up some parts of what I've done.

**Comment by sorgelig** [comment] 2020-06-22 09:51
My approach is different, so your fix is irrelevant. My code takes care of re-appearing other devices under the same devname.

**Comment by c0d3h4x0r** [comment] 2020-06-22 09:53
I just saw you posted a new release.  I'll try it out.

**Comment by c0d3h4x0r** [comment] 2020-06-22 09:59
Your fix solves all of the problems I found, so I'll close my PR.  Thank you!

**Comment by c0d3h4x0r** [comment] 2020-06-28 23:55
This still isn’t entirely fixed.  I’m still experiencing some cases where if my BT keyboard and BT gamepad both go to sleep and then wake up, neither one is recognized correctly by the core anymore.

**Comment by c0d3h4x0r** [comment] 2020-06-28 23:59
I’ll review your fix again, examine the console output of the `MiSTer` process during a repro, and see if I can figure out why this is still happening.

**Comment by c0d3h4x0r** [comment] 2020-06-29 00:05
Would you prefer for me to open a new issue with a new title to more accurately describe what I’m now seeing?

**Comment by c0d3h4x0r** [comment] 2020-06-29 00:59
I'll go ahead and open a new issue.
