### ISSUE TITLE
Freeze of the MiSTer app after changing core a lot of times

### ISSUE THREAD

**Issue by pocomane** [MiSTer-devel/Main_MiSTer#379] opened 2021-04-07 07:42 UTC
I got an [issue report for mbc](https://github.com/pocomane/MiSTer_Batch_Control/issues/7) about a freeze after a lot of rom changes. After a bit of investigation, I found it is probably a bug of the MiSTer app. I can reproduce it with the following command via ssh:

for (( ; ; )); do echo "load_core /media/fat/_Console/SNES_20210222.rbf" > /dev/MiSTer_cmd; date +%H:%M:%S; sleep 7; done;

After about 5 minutes, the MiSTer freezes and it does not accept anymore commands via keyboard or joypad. To recover, you have to relaunch the MiSTer app, i.e. in a ssh:

killall MiSTer
/media/fat/MiSTer &
disown

**Comment by mrchrisster** [comment] 2021-04-07 21:26
I just tested the core reload with an interval of 30s and I can confirm that the command failed after around 2 hours and would not accept any new input.

**Comment by mrchrisster** [comment] 2021-04-12 05:52
I can confirm this bug also exists in MiSTer_20210109 and MiSTer_20200608 (the two versions I tested so far)

**Comment by sorgelig** [comment] 2021-04-12 07:08
with every core load Main gets reloaded too. But since process gets reloaded from itself, probably some resources aren't freed on kernel level. So it's not easy to fix.

**Comment by bootsector** [comment] 2021-04-12 17:06
@pocomane aren't there any relevant messages in logs/dmesg that could help pinpointing where the issue lies?

**Comment by pocomane** [comment] 2021-04-12 19:59
At first sight, it does not seem so to me, but I do not know the Main_MiSTer internals very well, so I attached dmesg and Main_MiSTer output.

Note 1 about the infinite count of /devices/virtual/input/inputXX: if I restart Main_MiSTer it just restart counting from where it left. 
Note 2: if I press ^C after the freeze, Main_MiSTer prints "Exiting..." before quit, so at least the signal handler was not freezed.

[report.zip](https://github.com/MiSTer-devel/Main_MiSTer/files/6299439/report.zip)

**Comment by boogermann** [comment] 2021-04-13 02:02
@pocomane MiSTer doesn't actually have a proper signal handling in place. For instance, if you give a reboot command on linux, the application doesn't handle a SIGKILL to close it.

@sorgelig since the command @pocomane uses to reproduce the error doesn't necessary load any game or deal with any input, I know of 2 bugs that could get triggered simple by the fact that at every reload the routines execute it.

On the cfg.cpp there are 2 bug prone areas, since they make usage of memset and memcpy:

On [line 111](https://github.com/MiSTer-devel/Main_MiSTer/blob/master/cfg.cpp#L111), Initialization of 'ini_file' with static storage duration may throw an exception that cannot be caught. [ERR58-CPP. Handle all exceptions thrown before main() begins executing.](https://wiki.sei.cmu.edu/confluence/display/cplusplus/ERR58-CPP.+Handle+all+exceptions+thrown+before+main()+begins+executing)

On [line 271](https://github.com/MiSTer-devel/Main_MiSTer/blob/master/cfg.cpp#L271), it can trigger a [bugprone-undefined-memory-manipulation](https://clang.llvm.org/extra/clang-tidy/checks/bugprone-undefined-memory-manipulation.html)

There are some memory allocations that might be also missing a free command to clear them up. I'll give it a try and run it with valgrind to see if I catches any memory leak.

**Comment by bootsector** [comment] 2021-04-13 12:00
@boogermann it's pretty unlikely this is being caused by memory leak, as every reload would clear those, if any.

Since there's a lot of "Too many open files" error messages in the provided Main MiSTer logs, I would assume this is related to file descriptors exhaustion (not being properly freed?) on the OS/Linux side.

**Comment by sorgelig** [comment] 2021-04-13 14:28
It's kernel issue. MiSTer process gets reloaded with every core load, so it doesn't matter if some handles wasn't closed or freed. Kernel should do this instead. But somehow something hasn't freed on process re-load.

**Comment by zakk4223** [comment] 2021-04-14 23:06
No, this is not a kernel issue. Main_Mister is restarted via execl(), execve() DOES NOT close open file descriptors by default. See man page for execve()

`By  default,  file  descriptors remain open across an execve().  File descriptors that are marked close-on-exec are closed; see the description of FD_CLOEXEC in fcntl(2)`

Every "restart" of the the mister process on core load is likely leaking every open file descriptor, unless they've been set to FL_CLOEXEC. It's possible some are, depending on what some libraries are doing, but none of the ones explicitly opened in the mister source have that flag set.

There's two possible ways to fix this. 

You can loop through every file descriptor and set them to FD_CLOEXEC just before you execute the exec. Typically you'd do it via /proc/<pid>/fd but I think for Mister you can just do a loop from 3-1024 and be safe.

OR

You can wrap the MiSTer binary in a shell script that always restarts it if it exits with a certain return code, and then instead of execl in mister binary, just do exit(<special code>). The reason you set it up on a specific exit code is that allows you to still ssh in and kill MiSTer for development/debug purposes.

**Comment by sorgelig** [comment] 2021-04-15 18:26
in this line: https://github.com/MiSTer-devel/Main_MiSTer/blob/289943749974505fcfebd3b7b3380e61b49d7006/file_io.cpp#L397
try to replace ```mode``` by ```mode | O_CLOEXEC``` 
if it will fix the problem, then i will change it in the code.

**Comment by zakk4223** [comment] 2021-04-15 20:10
Most files in file_io are properly closed and not held open after use. The leaks are mostly from input and /dev/mem.

I think I have them all fixed, just running a stress test right now. I will send a PR when I'm confident the test isn't leaking descriptors over a large number of reloads.

**Comment by sorgelig** [comment] 2021-04-15 23:02
Actually i've just asked for test, not PR.
I will refactor the code for memory file.

**Comment by zakk4223** [comment] 2021-04-16 00:40
In that case changing that line of code resulted in no improvement

**Comment by sorgelig** [comment] 2021-04-16 15:14
i've just pushed commit to fix this issue

**Comment by bootsector** [comment] 2021-04-16 22:48
In case anyone wanna test: https://github.com/MiSTer-unstable-nightlies/Main_MiSTer/releases/download/unstable-builds/MiSTer_unstable_20210416_b492

**Comment by mrchrisster** [comment] 2021-04-17 03:01
I haven't checked anything else but I think you guys did it!
Have been running `for (( ; ; )); do echo "load_core /media/fat/_Console/SNES_20210225.rbf" > /dev/MiSTer_cmd; date +%H:%M:%S; sleep 7; done` for about an hour now and restart keeps working.
Just for sanity I checked 'MiSTer_20210404' again and it crashed after 10 minutes.

**Closed** 2021-10-04 10:57 UTC
