### ISSUE TITLE
Feature Request, Disable Auto-Fire Toggling

### ISSUE THREAD

**Issue by nintendesi** [MiSTer-devel/Main_MiSTer#405] opened 2021-05-28 04:46 UTC
Hello, I have a few suggestions about the auto-fire feature on the MiSTer, because I have been running into several frustrating experiences over the past few months while trying to work around this feature. At first, I decided I would learn to avoid accidentally mapping some buttons as I open the MiSTer menu, but over the months there have been instances when I still continue to map buttons to auto-fire. I have a highlight from an earlier stream I had today that displays some of the issues I was having with the feature: https://www.twitch.tv/videos/1036995364. I edited the highlight to show time stamps of spots before and after the moment occurred when I accidentally triggered auto-fire, and what resulted after.

If at all possible, I would sincerely appreciate it if the following suggestions could be considered for an update regarding the auto-fire feature:
1. Add an option to disable auto-fire completely across all cores.
2. Indicate somehow which buttons auto-fire has enabled. The highlight shows that auto-fire displayed a message multiple times that it shut itself off, but other buttons were still mapped to auto-fire.
3. Add an option to re-map the combination that enables auto-fire to prevent it from being accidentally triggered.

The problem is that often I go into the menu and navigate too quickly, accidentally enabling auto-fire without noticing it, leading to a frustrating experience. This especially happens if I am playing a game that has me spamming things involving the Up and Select buttons, and Zelda 2 (the game I stream most) very often has me using select to cast magic with a thumb on the D-Pad. Ideally, I'd just be able to disable auto-fire, but these are all the things I can think of that could improve the situation.

Alternatively, it would be possible to remap the buttons for the menu to something that wouldn't be so easy to trigger. If you notice the highlight with the input display, you will see that the NES controller has so few buttons, and the type of situation I encountered that caused auto-fire to trigger. With an economy of buttons, you have to make use of every button very often, especially in challenging situations. Of course, a workaround would be to unmap the menu from the controller and to use the menu button on the MiSTer itself, but this is not ideal for two reasons. It is easy to bump reset accidentally, and the MiSTer is rather distant from my office chair, meaning that every time I wanted to save the game or switch games or cores I would need to interrupt what I do.

Thank you very much for your time and help with this matter.

**Comment by sorgelig** [comment] 2021-05-28 06:10
For me it more look like your specific behavior than real issue. For example menu button isn't used in game play. Why you need to go to menu in challenging situations?

**Comment by SpaceNeurosis** [comment] 2021-05-28 07:17
Thanks for the quick response!

Nintendesi and I chatted about this earlier and I'm responding because he's live right now. 

There are two situations that contribute to what he's experiencing:
The one is that the on controllers with few buttons like the NES controller, it's relatively difficult to pick a menu combo can't be pressed accidentally during play - he plays very challenging Zelda 2 hacks and plays some games with a timer. 

The second situation is that trying to quickly access the menu, which is the recommended way to flush the save data, and getting back to the game can result in this happening as well.

The autofire enable/disable is relatively easy to miss and does not tell you which button had autofire enabled/disabled and there also does not seem to be a way to show the current status of autofire for all buttons which makes it difficult to know if you're going to run into an autofire issue.

I don't think any of these things individually are particularly problematic but the subtle interaction between all of these things can result in a confusing experience, especially for newer users who don't know about the autofire feature yet. There are probably several ways of addressing this, like giving the ability to lock the current autofire settings or just showing which button numbers have autofire enabled from the menu.

I could look at sending a PR for this if there is something to be done and would very much appreciate your input on how to think about this.

**Comment by sorgelig** [comment] 2021-05-28 20:13
May be it will be sufficient to add a system-wide option to disable autofire which won't be saved. So if you are going to play such game you can turn of the autofire in advance so it won't bother you till you re-load the core (or enable autofire on).

**Comment by M-Walrus** [comment] 2021-06-18 02:48
I think this would be a good addition.  Often times I will accidentally trigger this also, and depending on the controller used this can be quite easy to do, and then you don't always know which button got turbo without testing every single one.

**Comment by mysidia** [comment] 2021-06-23 21:49
Yes; I also had some of the extra key combinations trigger and activate accidentally from time to time  and with key combinations on the Menu button that do not seem to be customizable.      It's also a concern for attempting to challenge speedrun records or make other competitive achievements & people might doubt their validity if this Auto fire cheat may exist on the console at all, but:

It would be very useful to have a system-wide option from the OSD menu that can disable and Visually confirm that the autofire and extra button combos are temporarily inactivated, even if this does not save across reboot.

**Comment by NBeing** [comment] 2022-08-11 14:30
I can confirm that autofire being off by default would be a very helpful feature. As a community organizer for the fighting game community we encounter a very different use-case for Mister. While running tournaments we have a given game running and folks will plug in their controllers. A given setup can have 100 people a day with about that many different PCB's using it. 
Having auto-fire turn on mid tournament match invalidates that match and it happens often given that some controllers will have the menu button map to a button near normal game controls. 

Having a good workflow for disabling autofire would help the retro fighting game community a ton -- Even if its an INI setting or a hiddent configuration, it would be much appreciated.

**Comment by RumblePen** [comment] 2022-11-28 06:55
Just having an autofire key separate from the menu key would go a long ways. People with no interest in autofire can just not map that key. It gets tiresome having to turn off/on autofire every time you open and close the menu when you have F12 mapped to a button combination on a controller with zero spare unused buttons.

**Comment by M-Walrus** [comment] 2022-11-29 01:48
Making an extra key to bind is not the answer here IMO. That's not very practical with the limited number of buttons on most controllers folks use with MiSTer.

An ini setting to disable it globally would be ideal.  I thought about how a temporary disable might work, like a keyboard hotkey combination or something, and it still would be impractical having to remember to disable it every time.  Folks have to reload cores and re-boot their system for many different reasons, and having to remember to turn this off each time would be cumbersome.

**Comment by RumblePen** [comment] 2022-11-29 02:34
If you dont have enough buttons to bind autofire then you just dont bind it. Functionally equivalent to disabling it. But those with enough buttons can bind it and have the ability to both open menu and toggle autofire without all the conflicts of the current implementation. Try to open menu, autofire is toggled. Try to turn autofire back on/off, menu opens.

Personally, being able to turn it off in the .ini, which will be in the next update, is enough for me since I never use autofire.

**Comment by sorgelig** [comment] 2022-11-29 12:49
Requiring separate button for autofire is unreasonable as most controllers don't have such. When you define all buttons to PSX, then usually no free buttons will left.

Yes, INI option will be in next release.

**Comment by Chromagram** [comment] 2023-02-13 15:04
Sorry to pop in here after the resolution, but I'm on v230122 and I just CANNOT for the life of me see anything in the INI about disabling autofire. I scanned the entire thing line by line several times and I don't see it. Could someone possibly point me in the right direction?

**Comment by birdybro** [comment] 2023-02-14 07:31
https://github.com/MiSTer-devel/Main_MiSTer/blob/master/MiSTer.ini#L305-L306

The mister.ini on your sd card doesn't automatically update.

**Comment by Chromagram** [comment] 2023-02-14 11:00
That makes sense. Thank you!

**Closed** 2023-02-14 14:24 UTC
