### ISSUE TITLE
I hope to add a new function to the system

### ISSUE THREAD

**Issue by szuping** [MiSTer-devel/Main_MiSTer#852] opened 2023-11-14 08:09 UTC
I recently purchased a retrocastle mister console, but I found that its HDMI and RGB outputs have left and right channel lines reversed. If I can customize the left and right channels in the system and switch the left and right channels by myself, that should save a lot of mister console

**Comment by sorgelig** [comment] 2023-11-14 13:38
I don't remember such complains. Probably it's specific to retrocastle.
Both analog and HDMI audio channels are controlled by cores directly, not by Main. So it's impossible to switch it from Main without rework the framework where all cores will need update to get such function.
Overall it's not worth. Originally correctly designed HW doesn't need such workaround.

**Comment by szuping** [comment] 2023-11-14 13:42
> I don't remember such complains. Probably it's specific to retrocastle. Both analog and HDMI audio channels are controlled by cores directly, not by Main. So it's impossible to switch it from Main without rework the framework where all cores will need update to get such function. Overall it's not worth. Originally correctly designed HW doesn't need such workaround.

Yes, it looks like this. The left and right channels of other people's HDMI/RGB audio are correct. Only mine is wrong. Among HDMI/RGB/3.5mm, only the 3.5mm output is correct for the left and right channels.

**Comment by sorgelig** [comment] 2023-11-14 13:45
HDMI cannot be incorrect as left and right channels are programmatically marked and transferred through the same wires.
The only place where left/right can be swapped is analog.

**Comment by szuping** [comment] 2023-11-14 13:47
> HDMI 不可能不正確，因為左右通道以編程方式標記並通過相同的電線傳輸。 唯一可以交換左/右的地方是模擬。
I know many people doubt me, but every time I buy a product, I will test the left and right channels. I used three devices to test this HDMI, and I also made specially made left and right channel discs... The one on discord found pce-CD- I am the one who displays errors on the left and right channels of the VU meter...

**Comment by sorgelig** [comment] 2023-11-14 13:50
Oh, i see. You are the one reporting issue in TurboGrafx core. As @dshadoff told it can be specific to core implementation, so he will check it.

**Comment by szuping** [comment] 2023-11-14 13:52
> 我懂了。您是 TurboGrafx 核心中第一個報告問題的人。作為@dshadoff告訴它可以特定於核心實現，所以他會檢查它。

我購買速賣通或是淘寶的產品, 左右聲道錯誤率非常高, 兩個月內我手上處裡的4件....中國產品非常不注意這個, 我對他們經常弄錯感到不可思議, 如果你在台灣, 我可以將retrocastle寄給你測試

**Comment by sorgelig** [comment] 2023-11-14 13:52
Please use English

**Comment by szuping** [comment] 2023-11-14 13:52
When I buy products from AliExpress or Taobao, the error rate of the left and right channels is very high. Chinese products don't pay much attention to this. I am surprised that they made mistakes. If you are in Taiwan, I can send you a retrocastle for testing.

**Comment by sorgelig** [comment] 2023-11-14 13:54
Yes, i'm in Taiwan. But i'm not the manufacturer of retrocastle and i don't work for them, so you have to contact them if you have problem specific to this device.

**Comment by szuping** [comment] 2023-11-14 13:56
> I know, I just want to confirm that the way I tested the HDMI left and right channels is correct, but I think they have no intention of solving or acknowledging this problem.

**Comment by szuping** [comment] 2023-11-14 13:59
> 是的，我在台灣。但我不是 Retrocastle 的製造商，也不為他們工作，所以如果您遇到該設備有問題，您必須聯繫他們。
I informed him that day, and he said that maybe we have different perceptions of left and right... Most sellers who make mistakes have almost the same answer. I always find myself dumbfounded, and maybe I have to modify it myself. . ..

**Comment by marceloMedeiros** [comment] 2023-11-14 14:20
I also have a Retrocastle unit and yes, I can confirm (by testing with the 240p test suit audio test on the MD core) the analog output have the left and right channel swapped. Not a big deal IMO since i can just swap the left and right audio cables. The HDMI output of course isn't swapped. Also, as it has been pointed multiple times already, this is a Retrocastle's issue, not a MiSTer issue.

**Comment by szuping** [comment] 2023-11-14 14:22
>Thank you for your response. I will now remove the analog board to continue testing the HDMI output. I don’t understand why my HDMI is also upside down?

**Comment by marceloMedeiros** [comment] 2023-11-14 14:35
I dont see how it would be possible to the Retrocastle board affect HDMI audio in any way, they are not customizing or modding either the DE-10 nano or the mister software. I also didn't test audio on the PC-engine core, just on the genesis core. So if its swapped on the hdmi out only on the pc-engine cd core, maybe theres something incorrect on that core. Luckly a dev is already looking into it.

**Comment by birdybro** [comment] 2023-11-14 15:51
@dshadoff is already helping you in this issue --> https://github.com/MiSTer-devel/TurboGrafx16_MiSTer/issues/199 and it seems to be an issue with just one core in your particular setup, so you should keep working with him on it.

If you have a retrocastle with the sega saturn style output that uses a video DAC converter and if audio is output through it, a lot of sega saturn style AV cables have the Left and Right audio swapped unfortunately because of incorrect schematics on the internet.

**Comment by Kitrinx** [comment] 2023-11-14 16:32
> Given that some cables are wrong it might be a decent idea to have a mister.ini option that swaps the audio, but that still would be adding a feature to make up for the failure of hardware manufacturers (which shouldn't really be our problem). Not meaning this seriously, just saying that it's an observed known thing to happen on some odd setups with inappropriately manufactured cables (which are common).

I think this is just clutter to add such options, and only encourages people to be more careless with hardware manufacture. TG16 is trivial to fix if the channels are reversed, if it hasn't been already, otherwise, there's nothing to be done here imho, other than report it to retrocastle.

**Closed** 2023-11-23 07:15 UTC
